version: '3'
services:
  app:
    image: arube/3amlibrary:latest
    volumes:
    - ./config.json:/app/config.json # Mount the local config.json to /app/config.json inside the container
    networks:
      - mynetwork
  memcache:
    image: memcached:latest
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - mynetwork
networks:
  mynetwork: